CREATE TABLE IF NOT EXISTS msu_users (
                                         user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                         first_name VARCHAR(255) NOT NULL,
                                         last_name VARCHAR(255) NOT NULL,
                                         login VARCHAR(255) NOT NULL UNIQUE,
                                         password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS tasks (
                                     task_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     title VARCHAR(255) NOT NULL,
                                     description TEXT,
                                     deadline TIMESTAMP NOT NULL,
                                     subject VARCHAR(255) NOT NULL,
                                     priority VARCHAR(20) NOT NULL CHECK (priority IN ('HIGH', 'MEDIUM', 'LOW')),
                                     type_of_task VARCHAR(20) NOT NULL CHECK (type_of_task IN ('HOMEWORK', 'BIG_HOMEWORK', 'PRACTICE', 'PREPARATION')),
                                     started TIMESTAMP,
                                     finished TIMESTAMP,
                                     user_id INT NOT NULL REFERENCES msu_users(user_id) ON DELETE CASCADE
);

INSERT INTO msu_users (user_id, first_name, last_name, login, password)
VALUES
    (1, 'Иван', 'Иванов', 'ivanov', 'pass123'),
    (2, 'Мария', 'Петрова', 'petrova', 'qwerty'),
    (3, 'Алексей', 'Сидоров', 'sidorov', '123456')
ON CONFLICT (user_id) DO NOTHING;

INSERT INTO tasks (title, description, deadline, subject, priority, type_of_task, started, finished, user_id)
VALUES
    ('Математика', 'Решить уравнения', '2024-03-01 18:00:00', 'Математика', 'HIGH', 'HOMEWORK', '2024-02-25 10:00:00', NULL, 1),
    ('Физика', 'Лабораторная работа', '2024-03-05 23:59:00', 'Физика', 'MEDIUM', 'PRACTICE', NULL, NULL, 1),
    ('История', 'Подготовить доклад', '2024-02-28 12:00:00', 'История', 'LOW', 'BIG_HOMEWORK', '2024-02-27 15:30:00', '2024-02-28 10:00:00', 2),
    ('Химия', 'Прочитать главу 5', '2024-03-10 00:00:00', 'Химия', 'HIGH', 'PREPARATION', NULL, NULL, 3)
ON CONFLICT DO NOTHING;